### ISSUE TITLE
搜索支持google

### ISSUE THREAD

**Issue by usc** [v2er-app/Android#1]
感谢大佬，
请问搜索能否支持下google？
谢谢。

**Comment by sethcreate** [comment]
之前试过，Google 的搜索页面不好爬取（没有固定的selector规则）

**Comment by usc** [comment]
> 之前试过，Google 的搜索页面不好爬取（没有固定的selector规则）

感觉是否直接跳google搜索即可，带上关键词

**Comment by shiqizhenyes** [comment]
> > 之前试过，Google 的搜索页面不好爬取（没有固定的selector规则）
> 
> 感觉是否直接跳google搜索即可，带上关键词加上site

那样用户体验比较差，而且现在的搜索也没什么不好
