### ISSUE TITLE
可否在双击底栏时回顶或者刷新

### ISSUE THREAD

**Issue by zfro** [v2er-app/Android#14]
当前版本是 2.1.0-alpha.
另外建议在点了底栏图标之后让图标变色或者加点其他的效果，感觉比现在的更容易辨识。（不过好像也没啥必要。

**Comment by shiqizhenyes** [comment]
双击标题可以回到顶部，现在就是点击变色的

**Comment by shiqizhenyes** [comment]
> 当前版本是 2.1.0-alpha. 另外建议在点了底栏图标之后让图标变色或者加点其他的效果，感觉比现在的更容易辨识。（不过好像也没啥必要。

双击标题可以回到顶部，现在就是点击变色的
