### ISSUE TITLE
更换主页的第一个Tab和第二个Tab的内容，基于2.6.0-beta版本

### ISSUE THREAD

**Issue by cooaer** [v2er-app/Android#20]
第一个Tab名称修改为首页，顶部摆放常用的话题，如同官网一样，具体效果参见下图的B站首页；
第二个Tab，去除“今日热议”模块，仅负责“节点导航”功能；
大家感觉怎么样？

![image](https://user-images.githubusercontent.com/4060489/173881443-72289c9e-79ea-43f3-badd-1aa835d17d9b.png) ![image](https://user-images.githubusercontent.com/4060489/173881073-6369061a-278c-4acb-a334-427e60b7f79c.png)

**Comment by shiqizhenyes** [comment]
> 第一个Tab名称修改为首页，顶部摆放常用的话题，如同官网一样，具体效果参见下图的B站首页； 第二个Tab，去除“今日热议”模块，仅负责“节点导航”功能； 大家感觉怎么样？
> 
> ![image](https://user-images.githubusercontent.com/4060489/173881443-72289c9e-79ea-43f3-badd-1aa835d17d9b.png) ![image](https://user-images.githubusercontent.com/4060489/173881073-6369061a-278c-4acb-a334-427e60b7f79c.png)

首页那块会考虑一下，今日热议去掉会降低体验
