### ISSUE TITLE
[bug] 使用 Google 登录时无法正常进行二步验证

### ISSUE THREAD

**Issue by ShellWen** [v2er-app/Android#23]
在输入密码后，谷歌会跳转到二步验证的页面，但是 V2er 似乎并没有进行正确的处理。

![Screenshot_2022-12-30-23-44-21-167_me.ghui.v2er.jpg](https://user-images.githubusercontent.com/38996248/210088274-4c6b0198-2683-48a6-84bd-9cc6fbcd4bd8.jpg)

**Comment by snicoe** [comment]
似乎是webview无法拉起系统的2fa认证流程，通过硬件密钥登录才会有这个问题，不过这个bug是webview一直存在的，现在都是通过chrome登录再让chrome去拉起2fa。

**Comment by shiqizhenyes** [comment]
> 似乎是webview无法拉起系统的2fa认证流程，通过硬件密钥登录才会有这个问题，不过这个bug是webview一直存在的，现在都是通过chrome登录再让chrome去拉起2fa。

有些手机可以,有些手机不行,像我的三星手机就可以
