### ISSUE TITLE
希望优化一下 Accessibility  体验

### ISSUE THREAD

**Issue by cary-rowen** [v2er-app/Android#4]
您好，我是视障用户，使用 Android 辅助功能服务 Talkback 操作手机，希望开发者针对 Talkback 做一些适配，目前比较影响看帖效率的一点是在帖子列表页会先读出最后发表时间 Or 回复时间而后读帖子标题，希望将此顺序调换，使 TalkBack 先读标题而后读时间，这样达到了重要信息前置原则，可以提高访问效率，谢谢！

**Comment by sethcreate** [comment]
@cary-rowen Thanks, this will be resolved in next version.

**Comment by cary-rowen** [comment]
感谢开发者的快速回复，另外几个点也一并列出，大多都是缺失 android:contentDescription 属性致使屏幕阅读器无法读出元素的具体作用，我们一般称之为“缺少文本标签”。
1. 贴子内的感谢 Button 缺少文本标签；
2. 贴子内每层楼的 MoreMenu 缺少文本标签；
3. 贴子内右下角回贴按钮缺少文本标签；
4. 编辑回贴内容的 Send Button 缺少文本标签；
5. 主界面右上角的搜索缺少文本标签；
6. 主界面左上角的菜单按钮缺少文本标签；
P.S 如果使用 ImageView、ImageButton、CheckBox 或其他以图形方式传达信息的 View，都可使用 android:contentDescription 属性为该 View 提供内容标签。（不需要加上元素类型或状态，如，“回复”按钮直接给元素的android:contentDescription赋值为“回复”即可，而不是赋值为“回复按钮”）。
非常感谢。

**Comment by sethcreate** [comment]
@cary-rowen 已修复

**Comment by cary-rowen** [comment]
感谢开发大大的快速响应。
2.0.1 体验很好，有几个点可否再麻烦修改下：
1. 主界面右上角的搜索缺少文本标签；
2. 贴子内的文案可否更简洁，如：“回复列表中更多”直接改为“菜单”或“更多”，“发送感谢”按钮直接改为“感谢”；
非常感谢！

**Comment by cary-rowen** [comment]
该修复似乎在最新2.1.8中被破坏了。
@graycreate 您能调查一下吗，或者是否需要我重新开启一个 Issue？

**Comment by graycreate** [comment]
> 该修复似乎在最新2.1.8中被破坏了。
> 
> @graycreate 您能调查一下吗，或者是否需要我重新开启一个 Issue？

下一版会纠正，最近两天
