### ISSUE TITLE
希望能支持默认打开链接

### ISSUE THREAD

**Issue by Mr54233** [v2er-app/Android#7]
![image](https://user-images.githubusercontent.com/46802509/147522895-0d3678b1-8883-48ff-b930-ae26f9f17b3e.png)
![image](https://user-images.githubusercontent.com/46802509/147522901-2f18e046-1531-4097-837c-4710139ef664.png)
如图所示，这样就能直接在软件里打开对应的链接而不用跳转到浏览器再二次跳转

**Comment by shiqizhenyes** [comment]
> ![image](https://user-images.githubusercontent.com/46802509/147522895-0d3678b1-8883-48ff-b930-ae26f9f17b3e.png)
> ![image](https://user-images.githubusercontent.com/46802509/147522901-2f18e046-1531-4097-837c-4710139ef664.png)
> 如图所示，这样就能直接在软件里打开对应的链接而不用跳转到浏览器再二次跳转

会在下个大版本更新提供这个特性

**Comment by shiqizhenyes** [comment]
> ![image](https://user-images.githubusercontent.com/46802509/147522895-0d3678b1-8883-48ff-b930-ae26f9f17b3e.png) ![image](https://user-images.githubusercontent.com/46802509/147522901-2f18e046-1531-4097-837c-4710139ef664.png) 如图所示，这样就能直接在软件里打开对应的链接而不用跳转到浏览器再二次跳转

这个是安卓12 的一项行为变更，深度链接在默认浏览器打开，不在未认证的app打开，而这个认证需要服务器端做，目前这一块适配会有问题
